site_name: Gluu Cluster Docs 
site_description: Documenation for the Gluu Server Cluster
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2014, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/docs-cluster
theme: spacelab

theme_dir: ./theme/mkdocs/
theme_center_lead: false
include_search: true

pages:

# Home Page
- ['index.md', 'Home']

# Admin Guide Sections
- ['admin-guide/overview/index.md', 'Admin Guide', 'Overview']
- ['admin-guide/installation/index.md', 'Admin Guide', 'Installation']
- ['admin-guide/components/index.md', 'Admin Guide', 'Components']
- ['admin-guide/monitoring/index.md', 'Admin Guide', 'Monitoring']
- ['admin-guide/testing/index.md', 'Admin Guide', 'Testing']
- ['admin-guide/tuning/index.md', 'Admin Guide', 'Tuning']

# API section
- ['reference/api.md', 'Reference', 'API']
